const periodictabledata = [
    {
        name: "Hydrogen",
        atomicnumber: 1,
        symbol: "H",
        category: "Reactive nonmetal",
        atomicweight: "1.008",
        atomicweightfull: "[1.00784, 1.00811]",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 1,
        period: 1,
        block: "s",
        tablerow18col: 1,
        tablecolumn18col: 1,
        visible: true,
        electronConfiguration: "1s¹",
        valenceElectrons: 1
    },
    {
        name: "Helium",
        atomicnumber: 2,
        symbol: "He",
        category: "Noble gas",
        atomicweight: "4.0026",
        atomicweightfull: "4.002602(2)",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 1,
        block: "s",
        tablerow18col: 1,
        tablecolumn18col: 18,
        visible: true,
        electronConfiguration: "1s²",
        valenceElectrons: 2
    },
    {
        name: "Lithium",
        atomicnumber: 3,
        symbol: "Li",
        category: "Alkali metal",
        atomicweight: "6.94",
        atomicweightfull: "[6.938, 6.997]",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 1,
        period: 2,
        block: "s",
        tablerow18col: 2,
        tablecolumn18col: 1,
        visible: true,
        electronConfiguration: "(He)2s¹",
        valenceElectrons: 1
    },
    {
        name: "Beryllium",
        atomicnumber: 4,
        symbol: "Be",
        category: "Alkaline earth metal",
        atomicweight: "9.0122",
        atomicweightfull: "9.0121831(5)",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 2,
        period: 2,
        block: "s",
        tablerow18col: 2,
        tablecolumn18col: 2,
        visible: true,
        electronConfiguration: "(He)2s²",
        valenceElectrons: 2
    },
    {
        name: "Boron",
        atomicnumber: 5,
        symbol: "B",
        category: "Metalloid",
        atomicweight: "10.81",
        atomicweightfull: "[10.806, 10.821]",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 13,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 13,
        visible: true,
        electronConfiguration: "(He)2s²2p¹",
        valenceElectrons: 3
    },
    {
        name: "Carbon",
        atomicnumber: 6,
        symbol: "C",
        category: "Reactive nonmetal",
        atomicweight: "12.011",
        atomicweightfull: "[12.0096, 12.0116]",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 14,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 14,
        visible: true,
        electronConfiguration: "(He)2s²2p²",
        valenceElectrons: 4
    },
    {
        name: "Nitrogen",
        atomicnumber: 7,
        symbol: "N",
        category: "Reactive nonmetal",
        atomicweight: "14.007",
        atomicweightfull: "[14.00643, 14.00728]",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 15,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 15,
        visible: true,
        electronConfiguration: "(He)2s²2p³",
        valenceElectrons: 5
    },
    {
        name: "Oxygen",
        atomicnumber: 8,
        symbol: "O",
        category: "Reactive nonmetal",
        atomicweight: "15.999",
        atomicweightfull: "[15.99903, 15.99977]",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 16,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 16,
        visible: true,
        electronConfiguration: "(He)2s²2p⁴",
        valenceElectrons: 6
    },
    {
        name: "Fluorine",
        atomicnumber: 9,
        symbol: "F",
        category: "Reactive nonmetal",
        atomicweight: "18.998",
        atomicweightfull: "18.998403163(6)",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 17,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 17,
        visible: true,
        electronConfiguration: "(He)2s²2p⁵",
        valenceElectrons: 7
        
    },
    {
        name: "Neon",
        atomicnumber: 10,
        symbol: "Ne",
        category: "Noble gas",
        atomicweight: "20.18",
        atomicweightfull: "20.1797(6)",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 18,
        visible: true,
        electronConfiguration: "(He)2s²2p⁶",
        valenceElectrons: 8
    },
    {
        name: "Sodium",
        atomicnumber: 11,
        symbol: "Na",
        category: "Alkali metal",
        atomicweight: "22.99",
        atomicweightfull: "22.98976928(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 1,
        period: 3,
        block: "s",
        tablerow18col: 3,
        tablecolumn18col: 1,
        visible: true,
        electronConfiguration: "(Ne)3s¹",
        valenceElectrons: 1
    },
    {
        name: "Magnesium",
        atomicnumber: 12,
        symbol: "Mg",
        category: "Alkaline earth metal",
        atomicweight: "24.305",
        atomicweightfull: "[24.304, 24.307] ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 2,
        period: 3,
        block: "s",
        tablerow18col: 3,
        tablecolumn18col: 2,
        visible: true,
        electronConfiguration: "(Ne)3s²",
        valenceElectrons: 2
    },
    {
        name: "Aluminium",
        atomicnumber: 13,
        symbol: "Al",
        category: "Post-transition metal",
        atomicweight: "26.982",
        atomicweightfull: "26.9815384(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 13,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 13,
        visible: true,
        electronConfiguration: "(Ne)3s²3p¹",
        valenceElectrons: 3,
    },
    {
        name: "Silicon",
        atomicnumber: 14,
        symbol: "Si",
        category: "Metalloid",
        atomicweight: "28.085",
        atomicweightfull: "[28.084, 28.086] ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 14,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 14,
        visible: true,
        electronConfiguration: "(Ne)3s²3p²",
        valenceElectrons: 4
    },
    {
        name: "Phosphorus",
        atomicnumber: 15,
        symbol: "P",
        category: "Reactive nonmetal",
        atomicweight: "30.974",
        atomicweightfull: "30.973761998(5) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 15,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 15,
        visible: true,
        electronConfiguration: "(Ne)3s²3p³",
        valenceElectrons: 5
    },
    {
        name: "Sulfur",
        atomicnumber: 16,
        symbol: "S",
        category: "Reactive nonmetal",
        atomicweight: "32.06",
        atomicweightfull: "[32.059, 32.076] ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 16,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 16,
        visible: true,
        electronConfiguration: "(Ne)3s²3p⁴",
        valenceElectrons: 6
    },
    {
        name: "Chlorine",
        atomicnumber: 17,
        symbol: "Cl",
        category: "Reactive nonmetal",
        atomicweight: "35.45",
        atomicweightfull: "[35.446, 35.457] ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 17,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 17,
        visible: true,
        electronConfiguration: "(Ne)3s²3p⁵",
        valenceElectrons: 7
    },
    {
        name: "Argon",
        atomicnumber: 18,
        symbol: "Ar",
        category: "Noble gas",
        atomicweight: "39.95",
        atomicweightfull: "[39.792, 39.963] ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 18,
        visible: true,
        electronConfiguration: "(Ne)3s²3p⁶",
        valenceElectrons: 8
    },
    {
        name: "Potassium",
        atomicnumber: 19,
        symbol: "K",
        category: "Alkali metal",
        atomicweight: "39.098",
        atomicweightfull: "39.0983(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 1,
        period: 4,
        block: "s",
        tablerow18col: 4,
        tablecolumn18col: 1,
        visible: true,
        electronConfiguration: "(Ar)4s¹",
        valenceElectrons: 1
    },
    {
        name: "Calcium",
        atomicnumber: 20,
        symbol: "Ca",
        category: "Alkaline earth metal",
        atomicweight: "40.078",
        atomicweightfull: "40.078(4) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 2,
        period: 4,
        block: "s",
        tablerow18col: 4,
        tablecolumn18col: 2,
        visible: true,
        electronConfiguration: "(Ar)4s²",
        valenceElectrons: 2
    },
    {
        name: "Scandium",
        atomicnumber: 21,
        symbol: "Sc",
        category: "Transition metal",
        atomicweight: "44.956",
        atomicweightfull: "44.955908(5) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 3,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 3,
        visible: true,
        electronConfiguration: "(Ar)3d¹4s²",
        valenceElectrons: 3
    },
    {
        name: "Titanium",
        atomicnumber: 22,
        symbol: "Ti",
        category: "Transition metal",
        atomicweight: "47.867",
        atomicweightfull: "47.867(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 4,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 4,
        visible: true,
        electronConfiguration: "(Ar)3d²4s²",
        valenceElectrons: 4
    },
    {
        name: "Vanadium",
        atomicnumber: 23,
        symbol: "V",
        category: "Transition metal",
        atomicweight: "50.942",
        atomicweightfull: "50.9415(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 5,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 5,
        visible: true,
        electronConfiguration: "(Ar)3d³4s²",
        valenceElectrons: 5
    },
    {
        name: "Chromium",
        atomicnumber: 24,
        symbol: "Cr",
        category: "Transition metal",
        atomicweight: "51.996",
        atomicweightfull: "51.9961(6) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 6,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 6,
        visible: true,
        electronConfiguration: "(Ar)3d⁵4s¹",
        valenceElectrons: 6
    },
    {
        name: "Manganese",
        atomicnumber: 25,
        symbol: "Mn",
        category: "Transition metal",
        atomicweight: "54.938",
        atomicweightfull: "54.938043(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 7,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 7,
        visible: true,
        electronConfiguration: "(Ar)3d⁵4s²",
        valenceElectrons: 7
    },
    {
        name: "Iron",
        atomicnumber: 26,
        symbol: "Fe",
        category: "Transition metal",
        atomicweight: "55.845",
        atomicweightfull: "55.845(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 8,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 8,
        visible: true,
        electronConfiguration: "(Ar)3d⁶4s²",
        valenceElectrons: 8
    },
    {
        name: "Cobalt",
        atomicnumber: 27,
        symbol: "Co",
        category: "Transition metal",
        atomicweight: "58.933",
        atomicweightfull: "58.933194(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 9,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 9,
        visible: true,
        electronConfiguration: "(Ar)3d⁷4s²",
        valenceElectrons: 9
    },
    {
        name: "Nickel",
        atomicnumber: 28,
        symbol: "Ni",
        category: "Transition metal",
        atomicweight: "58.693",
        atomicweightfull: "58.6934(4) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 10,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 10,
        visible: true,
        electronConfiguration: "(Ar)3d⁸4s²",
        valenceElectrons: 10
    },
    {
        name: "Copper",
        atomicnumber: 29,
        symbol: "Cu",
        category: "Transition metal",
        atomicweight: "63.546",
        atomicweightfull: "63.546(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 11,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 11,
        visible: true,
        electronConfiguration: "(Ar)3d¹⁰4s¹",
        valenceElectrons: 11
    },
    {
        name: "Zinc",
        atomicnumber: 30,
        symbol: "Zn",
        category: "Post-transition metal",
        atomicweight: "65.38",
        atomicweightfull: "65.38(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 12,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 12,
        visible: true,
        electronConfiguration: "(Ar)3d¹⁰4s²",
        valenceElectrons: 12
    },
    {
        name: "Gallium",
        atomicnumber: 31,
        symbol: "Ga",
        category: "Post-transition metal",
        atomicweight: "69.723",
        atomicweightfull: "69.723(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 13,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 13,
        visible: true,
        electronConfiguration: "(Ar)3d¹⁰4s²4p¹",
        valenceElectrons: 13
    },
    {
        name: "Germanium",
        atomicnumber: 32,
        symbol: "Ge",
        category: "Metalloid",
        atomicweight: "72.63",
        atomicweightfull: "72.630(8) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 14,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 14,
        visible: true,
        electronConfiguration: "(Ar)3d¹⁰4s²4p²",
        valenceElectrons: 14
    },
    {
        name: "Arsenic",
        atomicnumber: 33,
        symbol: "As",
        category: "Metalloid",
        atomicweight: "74.922",
        atomicweightfull: "74.921595(6) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 15,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 15,
        visible: true,
        electronConfiguration: "(Ar)3d¹⁰4s²4p³",
        valenceElectrons: 15
    },
    {
        name: "Selenium",
        atomicnumber: 34,
        symbol: "Se",
        category: "Reactive nonmetal",
        atomicweight: "78.971",
        atomicweightfull: "78.971(8) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 16,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 16,
        visible: true,
        electronConfiguration: "(Ar)3d¹⁰4s²4p⁴",
        valenceElectrons: 16
    },
    {
        name: "Bromine",
        atomicnumber: 35,
        symbol: "Br",
        category: "Reactive nonmetal",
        atomicweight: "79.904",
        atomicweightfull: "[79.901, 79.907] ",
        occurrence: "Liquid",
        stateofmatter: "Primordial",
        group: 17,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 17,
        visible: true,
        electronConfiguration: "(Ar)3d¹⁰4s²4p⁵",
        valenceElectrons: 17
    },
    {
        name: "Krypton",
        atomicnumber: 36,
        symbol: "Kr",
        category: "Noble gas",
        atomicweight: "83.798",
        atomicweightfull: "83.798(2) ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 18,
        visible: true,
        electronConfiguration: "(Ar)3d¹⁰4s²4p⁶",
        valenceElectrons: 18
    },
    {
        name: "Rubidium",
        atomicnumber: 37,
        symbol: "Rb",
        category: "Alkali metal",
        atomicweight: "85.468",
        atomicweightfull: "85.4678(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 1,
        period: 5,
        block: "s",
        tablerow18col: 5,
        tablecolumn18col: 1,
        visible: true,
        electronConfiguration: "(Kr)5s¹",
        valenceElectrons: 1
    },
    {
        name: "Strontium",
        atomicnumber: 38,
        symbol: "Sr",
        category: "Alkaline earth metal",
        atomicweight: "87.62",
        atomicweightfull: "87.62(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 2,
        period: 5,
        block: "s",
        tablerow18col: 5,
        tablecolumn18col: 2,
        visible: true,
        electronConfiguration: "(Kr)5s²",
        valenceElectrons: 2
    },
    {
        name: "Yttrium",
        atomicnumber: 39,
        symbol: "Y",
        category: "Transition metal",
        atomicweight: "88.906",
        atomicweightfull: "88.90584(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 3,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 3,
        visible: true,
        electronConfiguration: "(Kr)4d¹5s²",
        valenceElectrons: 3
    },
    {
        name: "Zirconium",
        atomicnumber: 40,
        symbol: "Zr",
        category: "Transition metal",
        atomicweight: "91.224",
        atomicweightfull: "91.224(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 4,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 4,
        visible: true,
        electronConfiguration: "(Kr)4d²5s²",
        valenceElectrons: 4
    },
    {
        name: "Niobium",
        atomicnumber: 41,
        symbol: "Nb",
        category: "Transition metal",
        atomicweight: "92.906",
        atomicweightfull: "92.90637(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 5,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 5,
        visible: true,
        electronConfiguration: "(Kr)4d⁴5s¹",
        valenceElectrons: 5
    },
    {
        name: "Molybdenum",
        atomicnumber: 42,
        symbol: "Mo",
        category: "Transition metal",
        atomicweight: "95.95",
        atomicweightfull: "95.95(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 6,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 6,
        visible: true,
        electronConfiguration: "(Kr)4d⁵5s¹",
        valenceElectrons: 6
    },
    {
        name: "Technetium",
        atomicnumber: 43,
        symbol: "Tc",
        category: "Transition metal",
        atomicweight: "[97]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 7,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 7,
        visible: true,
        electronConfiguration: "(Kr)4d⁵5s²",
        valenceElectrons: 7
    },
    {
        name: "Ruthenium",
        atomicnumber: 44,
        symbol: "Ru",
        category: "Transition metal",
        atomicweight: "101.07",
        atomicweightfull: "101.07(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 8,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 8,
        visible: true,
        electronConfiguration: "(Kr)4d⁷5s¹",
        valenceElectrons: 8
    },
    {
        name: "Rhodium",
        atomicnumber: 45,
        symbol: "Rh",
        category: "Transition metal",
        atomicweight: "102.91",
        atomicweightfull: "102.90549(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 9,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 9,
        visible: true,
        electronConfiguration: "(Kr)4d⁸5s¹",
        valenceElectrons: 9
    },
    {
        name: "Palladium",
        atomicnumber: 46,
        symbol: "Pd",
        category: "Transition metal",
        atomicweight: "106.42",
        atomicweightfull: "106.42(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 10,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 10,
        visible: true,
        electronConfiguration: "(Kr)4d¹⁰5s⁰",
        valenceElectrons: 10
    },
    {
        name: "Silver",
        atomicnumber: 47,
        symbol: "Ag",
        category: "Transition metal",
        atomicweight: "107.87",
        atomicweightfull: "107.8682(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 11,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 11,
        visible: true,
        electronConfiguration: "(Kr)4d¹⁰5s¹",
        valenceElectrons: 11
    },
    {
        name: "Cadmium",
        atomicnumber: 48,
        symbol: "Cd",
        category: "Post-transition metal",
        atomicweight: "112.41",
        atomicweightfull: "112.414(4) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 12,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 12,
        visible: true,
        electronConfiguration: "(Kr)4d¹⁰5s²",
        valenceElectrons: 12
    },
    {
        name: "Indium",
        atomicnumber: 49,
        symbol: "In",
        category: "Post-transition metal",
        atomicweight: "114.82",
        atomicweightfull: "114.818(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 13,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 13,
        visible: true,
        electronConfiguration: "(Kr)4d¹⁰5s²5p¹",
        valenceElectrons: 13
    },
    {
        name: "Tin",
        atomicnumber: 50,
        symbol: "Sn",
        category: "Post-transition metal",
        atomicweight: "118.71",
        atomicweightfull: "118.710(7) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 14,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 14,
        visible: true,
        electronConfiguration: "(Kr)4d¹⁰5s²5p²",
        valenceElectrons: 14
    },
    {
        name: "Antimony",
        atomicnumber: 51,
        symbol: "Sb",
        category: "Metalloid",
        atomicweight: "121.76",
        atomicweightfull: "121.760(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 15,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 15,
        visible: true,
        electronConfiguration: "(Kr)4d¹⁰5s²5p³",
        valenceElectrons: 15
    },
    {
        name: "Tellurium",
        atomicnumber: 52,
        symbol: "Te",
        category: "Metalloid",
        atomicweight: "127.6",
        atomicweightfull: "127.60(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 16,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 16,
        visible: true,
        electronConfiguration: "(Kr)4d¹⁰5s²5p⁴",
        valenceElectrons: 16
    },
    {
        name: "Iodine",
        atomicnumber: 53,
        symbol: "I",
        category: "Reactive nonmetal",
        atomicweight: "126.9",
        atomicweightfull: "126.90447(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 17,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 17,
        visible: true,
        electronConfiguration: "(Kr)4d¹⁰5s²5p⁵",
        valenceElectrons: 17
    },
    {
        name: "Xenon",
        atomicnumber: 54,
        symbol: "Xe",
        category: "Noble gas",
        atomicweight: "131.29",
        atomicweightfull: "131.293(6) ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 18,
        visible: true,
        electronConfiguration: "(Kr)4d¹⁰5s²5p⁶",
        valenceElectrons: 18
    },
    {
        name: "Caesium",
        atomicnumber: 55,
        symbol: "Cs",
        category: "Alkali metal",
        atomicweight: "132.91",
        atomicweightfull: "132.90545196(6) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 1,
        period: 6,
        block: "s",
        tablerow18col: 6,
        tablecolumn18col: 1,
        visible: true,
        electronConfiguration: "(Xe)6s¹",
        valenceElectrons: 1
    },
    {
        name: "Barium",
        atomicnumber: 56,
        symbol: "Ba",
        category: "Alkaline earth metal",
        atomicweight: "137.33",
        atomicweightfull: "137.327(7) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 2,
        period: 6,
        block: "s",
        tablerow18col: 6,
        tablecolumn18col: 2,
        visible: true,
        electronConfiguration: "(Xe)6s²",
        valenceElectrons: 2
    },
    {
        name: "Lanthanum",
        atomicnumber: 57,
        symbol: "La",
        category: "Lanthanide",
        atomicweight: "138.91",
        atomicweightfull: "138.90547(7) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 3,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 3,
        visible: true,
        electronConfiguration: "(Xe)5d¹6s²",
        valenceElectrons: 3
    },
    {
        name: "Cerium",
        atomicnumber: 58,
        symbol: "Ce",
        category: "Lanthanide",
        atomicweight: "140.12",
        atomicweightfull: "140.116(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 4,
        visible: true,
        electronConfiguration: "(Xe)4f¹5d¹6s²",
        valenceElectrons: 4
    },
    {
        name: "Praseodymium",
        atomicnumber: 59,
        symbol: "Pr",
        category: "Lanthanide",
        atomicweight: "140.91",
        atomicweightfull: "140.90766(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 5,
        visible: true,
        electronConfiguration: "(Xe)4f³5d¹6s²",
        valenceElectrons: 5
    },
    {
        name: "Neodymium",
        atomicnumber: 60,
        symbol: "Nd",
        category: "Lanthanide",
        atomicweight: "144.24",
        atomicweightfull: "144.242(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 6,
        visible: true,
        electronConfiguration: "(Xe)4f⁴5d¹6s²",
        valenceElectrons: 6
    },
    {
        name: "Promethium",
        atomicnumber: 61,
        symbol: "Pm",
        category: "Lanthanide",
        atomicweight: "[145]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 7,
        visible: true,
        electronConfiguration: "(Xe)4f⁵5d¹6s²",
        valenceElectrons: 7
    },
    {
        name: "Samarium",
        atomicnumber: 62,
        symbol: "Sm",
        category: "Lanthanide",
        atomicweight: "150.36",
        atomicweightfull: "150.36(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 8,
        visible: true,
        electronConfiguration: "(Xe)4f⁶5d¹6s²",
        valenceElectrons: 8
    },
    {
        name: "Europium",
        atomicnumber: 63,
        symbol: "Eu",
        category: "Lanthanide",
        atomicweight: "151.96",
        atomicweightfull: "151.964(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 9,
        visible: true,
        electronConfiguration: "(Xe)4f⁷5d¹6s²",
        valenceElectrons: 9
    },
    {
        name: "Gadolinium",
        atomicnumber: 64,
        symbol: "Gd",
        category: "Lanthanide",
        atomicweight: "157.25",
        atomicweightfull: "157.25(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 10,
        visible: true,
        electronConfiguration: "(Xe)4f⁷5d¹6s²",
        valenceElectrons: 10
    },
    {
        name: "Terbium",
        atomicnumber: 65,
        symbol: "Tb",
        category: "Lanthanide",
        atomicweight: "158.93",
        atomicweightfull: "158.925354(8) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 11,
        visible: true,
        electronConfiguration: "(Xe)4f⁹5d¹6s²",
        valenceElectrons: 11
    },
    {
        name: "Dysprosium",
        atomicnumber: 66,
        symbol: "Dy",
        category: "Lanthanide",
        atomicweight: "162.5",
        atomicweightfull: "162.500(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 12,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁰5d¹6s²",
        valenceElectrons: 12
    },
    {
        name: "Holmium",
        atomicnumber: 67,
        symbol: "Ho",
        category: "Lanthanide",
        atomicweight: "164.93",
        atomicweightfull: "164.930328(7) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 13,
        visible: true,
        electronConfiguration: "(Xe)4f¹¹5d¹6s²",
        valenceElectrons: 13
    },
    {
        name: "Erbium",
        atomicnumber: 68,
        symbol: "Er",
        category: "Lanthanide",
        atomicweight: "167.26",
        atomicweightfull: "167.259(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 14,
        visible: true,
        electronConfiguration: "(Xe)4f¹²5d¹6s²",
        valenceElectrons: 14
    },
    {
        name: "Thulium",
        atomicnumber: 69,
        symbol: "Tm",
        category: "Lanthanide",
        atomicweight: "168.93",
        atomicweightfull: "168.934218(6) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 15,
        visible: true,
        electronConfiguration: "(Xe)4f¹³5d¹6s²",
        valenceElectrons: 15
    },
    {
        name: "Ytterbium",
        atomicnumber: 70,
        symbol: "Yb",
        category: "Lanthanide",
        atomicweight: "173.05",
        atomicweightfull: "173.045(10) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 16,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d¹6s²",
        valenceElectrons: 16
    },
    {
        name: "Lutenium",
        atomicnumber: 71,
        symbol: "Lu",
        category: "Lanthanide",
        atomicweight: "174.97",
        atomicweightfull: "174.9668(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 3,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d¹6s²",
        valenceElectrons: 17
    },
    {
        name: "Hafnium",
        atomicnumber: 72,
        symbol: "Hf",
        category: "Transition metal",
        atomicweight: "178.49",
        atomicweightfull: "178.49(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 4,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 4,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d²6s²",
        valenceElectrons: 18
    },
    {
        name: "Tantalum",
        atomicnumber: 73,
        symbol: "Ta",
        category: "Transition metal",
        atomicweight: "180.95",
        atomicweightfull: "180.94788(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 5,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 5,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d³6s²",
        valenceElectrons: 19
    },
    {
        name: "Tungsten",
        atomicnumber: 74,
        symbol: "W",
        category: "Transition metal",
        atomicweight: "183.84",
        atomicweightfull: "183.84(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 6,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 6,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d⁴6s²",
        valenceElectrons: 20
    },
    {
        name: "Rhenium",
        atomicnumber: 75,
        symbol: "Re",
        category: "Transition metal",
        atomicweight: "186.21",
        atomicweightfull: "186.207(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 7,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 7,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d⁵6s²",
        valenceElectrons: 21
    },
    {
        name: "Osmium",
        atomicnumber: 76,
        symbol: "Os",
        category: "Transition metal",
        atomicweight: "190.23",
        atomicweightfull: "190.23(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 8,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 8,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d⁶6s²",
        valenceElectrons: 22
    },
    {
        name: "Iridium",
        atomicnumber: 77,
        symbol: "Ir",
        category: "Transition metal",
        atomicweight: "192.22",
        atomicweightfull: "192.217(2) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 9,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 9,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d⁷6s²",
        valenceElectrons: 23
    },
    {
        name: "Platinum",
        atomicnumber: 78,
        symbol: "Pt",
        category: "Transition metal",
        atomicweight: "195.08",
        atomicweightfull: "195.084(9) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 10,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 10,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d⁹6s¹",
        valenceElectrons: 24
    },
    {
        name: "Gold",
        atomicnumber: 79,
        symbol: "Au",
        category: "Transition metal",
        atomicweight: "196.97",
        atomicweightfull: "196.966570(4) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 11,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 11,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d¹⁰6s¹",
        valenceElectrons: 25
    },
    {
        name: "Mercury",
        atomicnumber: 80,
        symbol: "Hg",
        category: "Post-transition metal",
        atomicweight: "200.59",
        atomicweightfull: "200.592(3) ",
        occurrence: "Liquid",
        stateofmatter: "Primordial",
        group: 12,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 12,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d¹⁰6s²",
        valenceElectrons: 26
    },
    {
        name: "Thallium",
        atomicnumber: 81,
        symbol: "Tl",
        category: "Post-transition metal",
        atomicweight: "204.38",
        atomicweightfull: "[204.382, 204.385] ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 13,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 13,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d¹⁰6s²6p¹",
        valenceElectrons: 27
    },
    {
        name: "Lead",
        atomicnumber: 82,
        symbol: "Pb",
        category: "Post-transition metal",
        atomicweight: "207.2",
        atomicweightfull: "207.2(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 14,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 14,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d¹⁰6s²6p²",
        valenceElectrons: 28
    },
    {
        name: "Bismuth",
        atomicnumber: 83,
        symbol: "Bi",
        category: "Post-transition metal",
        atomicweight: "208.98",
        atomicweightfull: "208.98040(1) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 15,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 15,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d¹⁰6s²6p³",
        valenceElectrons: 29
    },
    {
        name: "Polonium",
        atomicnumber: 84,
        symbol: "Po",
        category: "Post-transition metal",
        atomicweight: "[209]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 16,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 16,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d¹⁰6s²6p⁴",
        valenceElectrons: 30
    },
    {
        name: "Astatine",
        atomicnumber: 85,
        symbol: "At",
        category: "Metalloid",
        atomicweight: "[210]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 17,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 17,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d¹⁰6s²6p⁵",
        valenceElectrons: 31
    },
    {
        name: "Radon",
        atomicnumber: 86,
        symbol: "Rn",
        category: "Noble gas",
        atomicweight: "[222]",
        atomicweightfull: "-",
        occurrence: "Gas",
        stateofmatter: "From decay",
        group: 18,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 18,
        visible: true,
        electronConfiguration: "(Xe)4f¹⁴5d¹⁰6s²6p⁶",
        valenceElectrons: 32
    },
    {
        name: "Francium",
        atomicnumber: 87,
        symbol: "Fr",
        category: "Alkali metal",
        atomicweight: "[223]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 1,
        period: 7,
        block: "s",
        tablerow18col: 7,
        tablecolumn18col: 1,
        visible: true,
        electronConfiguration: "(Rn)7s¹",
        valenceElectrons: 1
    },
    {
        name: "Radium",
        atomicnumber: 88,
        symbol: "Ra",
        category: "Alkaline earth metal",
        atomicweight: "[226]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 2,
        period: 7,
        block: "s",
        tablerow18col: 7,
        tablecolumn18col: 2,
        visible: true,
        electronConfiguration: "(Rn)7s²",
        valenceElectrons: 2
    },
    {
        name: "Actinium",
        atomicnumber: 89,
        symbol: "Ac",
        category: "Actinide",
        atomicweight: "[227]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 3,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 3,
        visible: true,
        electronConfiguration: "(Rn)6d¹7s²",
        valenceElectrons: 3
    },
    {
        name: "Thorium",
        atomicnumber: 90,
        symbol: "Th",
        category: "Actinide",
        atomicweight: "232.04",
        atomicweightfull: "232.0377(4) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 4,
        visible: true,
        electronConfiguration: "(Rn)6d²7s²",
        valenceElectrons: 4
    },
    {
        name: "Protactinium",
        atomicnumber: 91,
        symbol: "Pa",
        category: "Actinide",
        atomicweight: "231.04",
        atomicweightfull: "231.03588(1) ",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 5,
        visible: true,
        electronConfiguration: "(Rn)5f²6d¹7s²",
        valenceElectrons: 5
    },
    {
        name: "Uranium",
        atomicnumber: 92,
        symbol: "U",
        category: "Actinide",
        atomicweight: "238.03",
        atomicweightfull: "238.02891(3) ",
        occurrence: "Solid",
        stateofmatter: "Primordial",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 6,
        visible: true,
        electronConfiguration: "(Rn)5f³6d¹7s²",
        valenceElectrons: 6
    },
    {
        name: "Neptunium",
        atomicnumber: 93,
        symbol: "Np",
        category: "Actinide",
        atomicweight: "[237]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 7,
        visible: true,
        electronConfiguration: "(Rn)5f⁴6d¹7s²",
        valenceElectrons: 7
    },
    {
        name: "Plutonium",
        atomicnumber: 94,
        symbol: "Pu",
        category: "Actinide",
        atomicweight: "[244]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "From decay",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 8,
        visible: true,
        electronConfiguration: "(Rn)5f⁶7s²",
        valenceElectrons: 8
    },
    {
        name: "Americium",
        atomicnumber: 95,
        symbol: "Am",
        category: "Actinide",
        atomicweight: "[243]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 9,
        visible: true,
        electronConfiguration: "(Rn)5f⁷7s²",
        valenceElectrons: 9
    },
    {
        name: "Curium",
        atomicnumber: 96,
        symbol: "Cm",
        category: "Actinide",
        atomicweight: "[247]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 10,
        visible: true,
        electronConfiguration: "(Rn)5f⁷7s²",
        valenceElectrons: 10
    },
    {
        name: "Berkelium",
        atomicnumber: 97,
        symbol: "Bk",
        category: "Actinide",
        atomicweight: "[247]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 11,
        visible: true,
        electronConfiguration: "(Rn)5f⁹7s²",
        valenceElectrons: 11
    },
    {
        name: "Californium",
        atomicnumber: 98,
        symbol: "Cf",
        category: "Actinide",
        atomicweight: "[251]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 12,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁰7s²",
        valenceElectrons: 12
    },
    {
        name: "Einsteinium",
        atomicnumber: 99,
        symbol: "Es",
        category: "Actinide",
        atomicweight: "[252]",
        atomicweightfull: "-",
        occurrence: "Solid",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 13,
        visible: true,
        electronConfiguration: "(Rn)5f¹¹7s²",
        valenceElectrons: 13
    },
    {
        name: "Fermium",
        atomicnumber: 100,
        symbol: "Fm",
        category: "Actinide",
        atomicweight: "[257]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 14,
        visible: true,
        electronConfiguration: "(Rn)5f¹²7s²",
        valenceElectrons: 14
    },
    {
        name: "Mendelevium",
        atomicnumber: 101,
        symbol: "Md",
        category: "Actinide",
        atomicweight: "[258]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 15,
        visible: true,
        electronConfiguration: "(Rn)5f¹³7s²",
        valenceElectrons: 15
    },
    {
        name: "Nobelium",
        atomicnumber: 102,
        symbol: "No",
        category: "Actinide",
        atomicweight: "[259]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 16,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴7s²",
        valenceElectrons: 16
    },
    {
        name: "Lawrencium",
        atomicnumber: 103,
        symbol: "Lr",
        category: "Actinide",
        atomicweight: "[266]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 0,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 3,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d¹7s²",
        valenceElectrons: 17
    },
    {
        name: "Rutherfordium",
        atomicnumber: 104,
        symbol: "Rf",
        category: "Transition metal",
        atomicweight: "[267]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 4,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 4,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d²7s²",
        valenceElectrons: 18
    },
    {
        name: "Dubnium",
        atomicnumber: 105,
        symbol: "Db",
        category: "Transition metal",
        atomicweight: "[268]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 5,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 5,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d³7s²",
        valenceElectrons: 19
    },
    {
        name: "Seaborgium",
        atomicnumber: 106,
        symbol: "Sg",
        category: "Transition metal",
        atomicweight: "[269]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 6,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 6,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d⁴7s²",
        valenceElectrons: 20
    },
    {
        name: "Bohrium",
        atomicnumber: 107,
        symbol: "Bh",
        category: "Transition metal",
        atomicweight: "[270]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 7,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 7,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d⁵7s²",
        valenceElectrons: 21
    },
    {
        name: "Hassium",
        atomicnumber: 108,
        symbol: "Hs",
        category: "Transition metal",
        atomicweight: "[269]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 8,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 8,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d⁶7s²",
        valenceElectrons: 22
    },
    {
        name: "Meitnerium",
        atomicnumber: 109,
        symbol: "Mt",
        category: "Unknown",
        atomicweight: "[278]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 9,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 9,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d⁷7s²",
        valenceElectrons: 23
    },
    {
        name: "Darmstadtium",
        atomicnumber: 110,
        symbol: "Ds",
        category: "Unknown",
        atomicweight: "[281]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 10,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 10,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d⁸7s²",
        valenceElectrons: 24
    },
    {
        name: "Roentgenium",
        atomicnumber: 111,
        symbol: "Rg",
        category: "Unknown",
        atomicweight: "[282]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 11,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 11,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d⁹7s²",
        valenceElectrons: 25
    },
    {
        name: "Copernicum",
        atomicnumber: 112,
        symbol: "Cn",
        category: "Post-transition metal",
        atomicweight: "[285]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 12,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 12,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d¹⁰7s²",
        valenceElectrons: 26
    },
    {
        name: "Nihonium",
        atomicnumber: 113,
        symbol: "Nh",
        category: "Unknown",
        atomicweight: "[286]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 13,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 13,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d¹⁰7s²7p¹",
        valenceElectrons: 27
    },
    {
        name: "Flerovium",
        atomicnumber: 114,
        symbol: "Fl",
        category: "Unknown",
        atomicweight: "[289]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 14,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 14,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d¹⁰7s²7p²",
        valenceElectrons: 28
    },
    {
        name: "Moscovium",
        atomicnumber: 115,
        symbol: "Mc",
        category: "Unknown",
        atomicweight: "[290]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 15,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 15,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d¹⁰7s²7p³",
        valenceElectrons: 29
    },
    {
        name: "Livermorium",
        atomicnumber: 116,
        symbol: "Lv",
        category: "Unknown",
        atomicweight: "[293]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 16,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 16,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d¹⁰7s²7p⁴",
        valenceElectrons: 30
    },
    {
        name: "Tennessine",
        atomicnumber: 117,
        symbol: "Ts",
        category: "Unknown",
        atomicweight: "[294]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 17,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 17,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d¹⁰7s²7p⁵",
        valenceElectrons: 31
    },
    {
        name: "Oganesson",
        atomicnumber: 118,
        symbol: "Og",
        category: "Unknown",
        atomicweight: "[294]",
        atomicweightfull: "-",
        occurrence: "Unknown",
        stateofmatter: "Synthetic",
        group: 18,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 18,
        visible: true,
        electronConfiguration: "(Rn)5f¹⁴6d¹⁰7s²7p⁶",
        valenceElectrons: 32
    },
]
